### ISSUE TITLE
Guide pages - reviewing navigation

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_guides#1]
Related to localgovdrupal/localgov_services#6

https://new.croydon.gov.uk/adult-health-and-social-care/paying-adult-social-care

Initial impression:
 - Recreates book module functionality with an enforced two tier (book, page) navigation. 
   - Pages have next/previous buttons
   - Pages have an entity reference to their 'Book' (Guide Homepage)
   - 'Book' (Guide Homepage) automatically has it's pages added to an entity reference and where they can be re-ordered
   - Pages can have a title and a 'section title', assume this is the option to show something different on the 'Book' (Guide Homepage)? It doesn't seem to be used, and these compulsory fields have the same value in all but the first two entries in the dump I checked.
 - Integrates into Services
   - Pages can (optionally) be placed into Service Hub (landing page) and Sub Hub (sublanding page)
      - Reviewing the db dump some are not put in any, most are put in a Serivce Hub (landing page), some are put in a Service Hub (landing page) and a Sub Hub (sublanding page), and a few are only put in a Sub Hub (sublanding page).
    - Book (Guide Homepage) works like a Service Sublanding page (with automated links to its pages), but how is it put into the Service? Where does it get it's path and breadcrumb from? The path auto I see is only the title.

Not that this makes things easier at first look for my task on localgovdrupal/localgov_services#6 but I get the sense that what would be desired is that:

 - Guides can stand alone as a type of two level navigation with automatic links to Pages from Book (Guide Homepage), and with previous/next links on the pages, and a link to their Parent Book (Guide Homepage).
 - Guide Parent Book (Guide Homepage) can be placed into services at the same level as Sub Landing pages.
 - Pages are put into the Book (Guide Homepage)
 - If the guide is in a service, the breadcrumb on the Parent Book (Guide Homepage) is Service > Book; and then on the page it is Service > Book > Page
  - If the guide is not in a service the breadcrumb is Book; and Book > Page.

Or are there use cases here for the fact it's the pages that are put into the Service not the Guide Homepage? How does that Homepage get the breadcrumb again? Are there use cases where the Guide homepage is at the Page level of the Services navigation not the sublanding page (thus creating a four tier navigation through the side route)?

**Comment by ekes** [comment]
@andybroomfield @lbcwebmaster @bhccwebmaster Are you the folks that can clarify any of the questions in there?

**Comment by andybroomfield** [comment]
Self assigned and will investigate monday.

**Comment by andybroomfield** [comment]
> * If the guide is in a service, the breadcrumb on the Parent Book (Guide Homepage) is Service > Book; and then on the page it is Service > Book > Page
> * If the guide is not in a service the breadcrumb is Book; and Book > Page.

This is correct.
In general, Guides are something that can be a drop in replacement for a service standard page if there is more indepth explanitory content (like a how to). Usually all guides fit into services. I'm not sure if there are any on the BHCC site that are outside, sometimes they can be when not published, though the fallback to just the guide path structure if not part of a service makes sense.
