### ISSUE TITLE
Rationalise Guide/ Step by Step/ Service landing page summary and description

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_guides#108]
Following on from [#243](https://github.com/localgovdrupal/localgov/issues/243), where we're proposing to open all summaries by default

The content group is confused by separate fields on guides and step by step for descriptions and summaries

![Image](https://user-images.githubusercontent.com/708140/234366869-31374706-af6f-4648-a535-77fb375ca006.png)

![Image](https://user-images.githubusercontent.com/708140/234366903-cf049dc8-ebe3-47ef-aa6f-cc0a7c8b38f1.png)

To be consistent with other content formats, we should investigate the impact of removing the description field and using the summary field instead

Some councils may have used both fields or the summary field alone. How do we manage this?

**Comment by willguv** [comment]
@stephen-cox one to discuss

**Comment by willguv** [comment]
This applies to service landing pages too

**Comment by andybroomfield** [comment]
Summary is part of the body field, though we might be able to 'hide' the body.
Also just rename description summary and hide body?

**Comment by stephen-cox** [comment]
Looking at the display modes, we don't seem to be using the summary on Guide Overview pages. We are using the summary in the teaser view of Step-by-step Overview pages. The teaser of Guide Overview pages uses the description.

We'll need to double check the code to see if they're used elsewhere, but could use the description in teaser views and just hide the summary or remove the description field and use the summary instead.

**Comment by keelanfh** [comment]
As I was just looking at this today, screenshot of this issue in step-by-step pages:

![image](https://github.com/localgovdrupal/localgov_guides/assets/19519457/52af0e35-3dc1-4311-9085-ae4a3fa6de11)

**Comment by willguv** [comment]
@stephen-cox to propose next steps

**Comment by stephen-cox** [comment]
| Content type          | Body | Summary | Custom description |
|-----------------------|------|---------|--------------------|
| Service landing page  | Not used | Used as lede and in teaser | N/A |
| Guide overview        | Yes | Used as lede for overview and page | Used in teaser |
| Guide page            | Yes | Used in teaser (closed by default) | N/A |
| Step by step overview | Yes | Used as lede and in teaser | Present but unused? |
| Step by step page     | Yes | Used as lede and in teaser (closed by default) | N/A |

@willguv I've tried to summarise the different configurations above.

For service landing pages the body and summary are displayed on the node edit page, but only the summary is displayed on the content page. I know some councils are using the body field, so perhaps we should just have this displayed on content pages?

The differences between guide and step by steps are:

The summary on the guide overviews is used as the lede on guide pages, while on step by step this summary is used for lede as usual.

Guide overviews have a separate description that is only used in teaser views. Step by step overviews have a separate description that looks complete unused to me.

From this I think removing the separate descriptions on the overview pages makes sense and for guides use the summary in teaser views. The only problem with removing fields is we still need to support installs where the fields still exist, so we'll need to be careful to ensure we don't break existing sites.

**Comment by willguv** [comment]
Stephen and Will agreed to:

- Remove Description fields for Guide Overview and Step by Step Overview, ensuring that the theme still support these fields
- Unhide by default the Summary fields in the Guide Page and Step by Step Page

**Comment by stephen-cox** [comment]
There are PRs removing description field from guide and step by step overview pages and showing the summary for the respective pages here:

- https://github.com/localgovdrupal/localgov_guides/pull/134
- https://github.com/localgovdrupal/localgov_step_by_step/pull/92

**Comment by finnlewis** [comment]
@ekes asked: "Might the description fields have been used in meta tags or search indexes anywhere"?

Worth a double check?

**Comment by stephen-cox** [comment]
>  "Might the description fields have been used in meta tags or search indexes anywhere"?

I did grep the config looking for uses of these fields and couldn't find any beyond those listed in the table above

**Comment by stephen-cox** [comment]
This has been done. Closing!
