### ISSUE TITLE
Make the word 'overview' editable

### ISSUE THREAD

**Issue by benhillsjones** [localgovdrupal/localgov_guides#113]
This issue was discussed and agreed in the new content design monthly Meetup today.

When you add a guide overview, the word 'overview' appears at the first page, and you cannot change it. Almost every council has amended this so they can change it.

The request is to make this editable in the core theme for everyone

**Comment by andybroomfield** [comment]
To use the same value as the guide section title, replace
````twig
<h2>{{ 'Overview'|t }}</h2>
{{ content }}
````
with
````twig
<h2>{{ content.localgov_guides_section_title }}</h2>
{{ content|without(localgov_guides_section_title) }}
````
in node--localgov-guides-overview--full.html.twig
