### ISSUE TITLE
Accessibility of guides

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_guides#118]

**Comment by willguv** [comment]
As discussed in the content meeting on 20/06/23 a lot of councils have been making bespoke changes to guides. This has happened at haringey and Essex. Essex have presented evidence on accessibility testing showing that screen reader users prefer one single column of navigation, not the columns approach.

Suggested changes: 

- Add the page name to the next and previous buttons (as per GDS) 
- Stack the guide nav vertically https://www.gov.uk/government/collections/homes-for-ukraine-sponsor-guides
- Shazia mentioned some research they have done at Invuse indicated there should be a skip to content option

Haringey example - https://new.haringey.gov.uk/council-tax/council-tax-payments-refunds/pay-your-council-tax

**Comment by keelanfh** [comment]
Skip link for the guide navigation was introduced in https://github.com/localgovdrupal/localgov_base/pull/443 but would be interested in Invuse's research on this too, e.g. on wording.

Related open issues:

https://github.com/localgovdrupal/localgov_base/issues/360 - if the wide menu is an issue, the wide body text probably is too - to my knowledge, guides are the only content type in LGD which has this width
https://github.com/localgovdrupal/localgov_base/issues/422

**Comment by finnlewis** [comment]
Essex example : 

https://www.essex.gov.uk/births-ceremonies-and-deaths/get-married-or-form-civil-partnership/essex-register-office

![Image](https://github.com/localgovdrupal/localgov_guides/assets/326588/c98b43fd-2a96-4b4a-b60e-d673f1aace43)

**Comment by finnlewis** [comment]
Discussing this in content group meeting: 

 - skip to content is already there (Keelen)
 - plus one for a configurable option to display as is or including the title of hte next page. See Keelen's comment on  https://github.com/localgovdrupal/localgov_base/issues/422#issuecomment-1486643643

**Comment by finnlewis** [comment]
Moving #422 to 'todo' column in product backlog group.

**Comment by willguv** [comment]
Closing this in favour of more specific issues
