### ISSUE TITLE
Show title in navigation links by default

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_guides#129]
With #125 there is now an option to show titles in the guide previous and next navigation buttons, but this needs turning on. Should we be showing them by default?

By default they look like:

![image](https://github.com/localgovdrupal/localgov_guides/assets/7189914/9e567a3b-ad13-4499-b7d1-ba1e69a42a82)

With titles enabled they look like:

![image](https://github.com/localgovdrupal/localgov_guides/assets/7189914/80d21fa0-2139-4b91-91ba-f48214851653)

**Comment by keelanfh** [comment]
From previous discussion of this, we didn't want to change behaviour of existing sites. But I'd be in favour of enabling for new installs.
