### ISSUE TITLE
Add a "skip the guide navigation" link at the top of the in-page guide navigation. 

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_guides#136]
@Shaz46726 raised the suggestion of added a visually-hidden-til-focused skip link at the beginning of the guide menu to allow keyboard users to skip over the in-page repeated navigation. 

Can you add some more information @Shaz46726 ?

**Comment by markconroy** [comment]
We have this feature already. I built it for us last year.

![Screenshot 2023-11-15 at 12 38 23](https://github.com/localgovdrupal/localgov_guides/assets/2183332/c302a859-d0c9-4aeb-bfb7-e34818fdb8c5)

**Comment by markconroy** [comment]
For reference, it's here: https://github.com/localgovdrupal/localgov_base/blob/1.x/templates/block/guides-contents-block.html.twig#L20

**Comment by msayoung** [comment]
So you did - thanks @markconroy :) 
I'll close this then.
