### ISSUE TITLE
Seeing fatal error on guides with unpublshed children

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_guides#159]
Seeing this error 

> TypeError: array_filter(): Argument 1 ($array) must be of type array, null given in array_filter() (line 113 of modules/contrib/localgov_guides/src/Plugin/Block/GuidesAbstractBaseBlock.php).

Still trying to work this out, in terms of steps to repliacate as not all devs seem to, but does happen on our Acquia environment.
1) Create a guide overview and a set of guide pages, but leave them unpublished.
2) Visit the guide overview page

Error will appear.
This might have occured due to the change in  #157 as that is now fetching a translation which I assume won't exist if its not published?

**Comment by andybroomfield** [comment]
Oddly publishing a single child page and then unpublishing it resolves the issue

**Comment by andybroomfield** [comment]
This is happening because on some guides, the contents of `localgov_guides_pages->referencedEntities()` is empty, up until the point a guide page (or overview) is saved. Not sure if this is a new or old issue, we've seen guides being out of sync before.
In terms of resolving the WSOD error, I suggest initialising guidePages to an empty array. `$this->guidePagess = []` and change the check from `if (is_null($this->guidePages)) {` to `if (empty($this->guidePages)) {`.
It will still show a blank menu, but should allow the guides to display until they are resaved. Maybe we need an update to fix them.

**Comment by ekes** [comment]
Can we also create a test with unpublished children? Maybe even with unpublished translation.

**Comment by finnlewis** [comment]
It does look like this was introduced with https://github.com/localgovdrupal/localgov_guides/commit/a409342a97cac3bc9392bd666d4871cbb5871dfe in the last release.

And good call @ekes for a test that includes unpublished guide pages.

**Comment by stephen-cox** [comment]
I'm not able to reproduce this specific issue, but there's a fix for this error here #160

**Comment by ekes** [comment]
Think this is fixed? Can we close?

**Comment by andybroomfield** [comment]
Yes fixed.
