### ISSUE TITLE
Guides - issues found in initial content testing

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_guides#19]
1) On landing page eg https://localgovdrupal.agile.coop/adult-health-and-social-care/travel-passes-and-support, the incorrect summary is being shown. Should be seeing content in [Guide description] and not the first xx chars of Body

2) The grey links panel should include a link to the overview, and use [Guide section title] as the wording

3) Guide pages should use the title of the Guide overview [title] as the title. See https://new.croydon.gov.uk/adult-health-and-social-care/travel-passes-and-support/blue-badges/blue-badges-organisations for an example

**Comment by willguv** [comment]
Hi @stephen-cox you asked me to check something - can't find your comment sorry

1) seems to be fixed

2) and 3) don't seem to be - talk at stand up?

**Comment by stephen-cox** [comment]
Hi @willguv 1 and 2 should now be fixed:
1. https://localgovdrupal.agile.coop/adult-health-and-social-care/travel-passes-and-support
2. https://localgovdrupal.agile.coop/adult-health-and-social-care/travel-passes-and-support/blue-badges

As discussed at standup, 3 is a tricker problem so I have created a separate issue for this here: https://github.com/localgovdrupal/localgov/issues/87
