### ISSUE TITLE
Guide overview won't save with unpublished Guide page

### ISSUE THREAD

**Issue by OliverHannan** [localgovdrupal/localgov_guides#40]
unable to Save Guide overview pages that have one or more unpublished Guide pages.

**Comment by j4-m** [comment]
Hi @OliverHannan could you provide a little more information on how to reproduce this error, specifically:

1. Steps to reproduce
2. What is currently happening? E.g. an error message? White screen?
3. What you expected to happen

Thanks!

**Comment by OliverHannan** [comment]
Hi @j4-m Just pulling something together now. Orginal error wasn't mine, is just hastily copied these across. Lesson learned, should have allocated to the orginal person, now lost in time.

**Comment by OliverHannan** [comment]
HI @j4-m 

Thanks to @danchamp schooling me on GitHub [it looks like this has been fixed elsewhere. ](https://github.com/localgovdrupal/localgov_guides/pull/27)

Let me know if you agree and then we can close?

I'll check these other Guides issues as well, bad idea just adding them.

**Comment by j4-m** [comment]
@OliverHannan yes it certainly sounds like it's related. #27 was released in the `1.0.0-alpha3` version of Guides a few months back so perhaps this module needs updating? If you're able to provide some brief instructions on how to reproduce the problem I'd be happy to test `1.0.0-alpha3` locally.

**Comment by OliverHannan** [comment]
@j4-m Sorry, i'm not able to just yet. Waiting on another update to our version of the site and will report back

**Comment by OliverHannan** [comment]
Hi @j4-m 

So, the issue _was_ that guide Overview pages couldn't be saved if there were any other unpublished guide pages associated with it. 

To reproduce you need to create a Guide overview pages and a couple of Guide pages to go with it. One of these Guide pages needs to have status of unpublished. The orginal issue meant the Guide overview page then couldn't be saved/updated. 

We can't recreate that issue anymore. 

[Here's the Overview guide page I made](https://dev.londoncouncils.gov.uk/my-guide-overview)

Here's the Guide pages

[Published](https://dev.londoncouncils.gov.uk/my-guide-overview/published-guide-page)

[Unpublished](https://dev.londoncouncils.gov.uk/my-guide-overview/unpublished-guide-page)

[Another published guide page](https://dev.londoncouncils.gov.uk/my-guide-overview/third-guide-page)

**Comment by danchamp** [comment]
There is a different issue though - on that overview page while anonymous the 'Next' link points to the unpublished guide page.

**Comment by Adnan-cds** [comment]
Related #36
