### ISSUE TITLE
Remove option for list styles on Guide Overview pages

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_guides#62]
From the localgov_base working group call today, @markconroy mentioned that we need to remove the ability to select the list format. 

@markconroy could you just confirm which item to remove? 

Was it the dashes?

**Comment by markconroy** [comment]
@finnlewis dashes, yes.

**Comment by markconroy** [comment]
Let's close this, as @danchamp has created the issue in the guides repo

**Comment by finnlewis** [comment]
@markconroy just to note, this issue is also in the localgov_guides repository, and it looks like @danchamp [closed the other one](https://github.com/localgovdrupal/localgov_guides/issues/61). Let's re-open this one.

From #61 :

> The localgov_base theme has removed the CSS and template support for dashes, due to an accessibility issue.
> Editors should no longer be given the option to use dashes in the Guide Overview list format.
> See: localgovdrupal/localgov_base#18

**Comment by finnlewis** [comment]
Did you start on this @danchamp ?

If not, I can take a look after standup.

**Comment by finnlewis** [comment]
Feel free to assign back to me.

**Comment by danchamp** [comment]
No problem @finnlewis, I'll pick this up this morning thanks.

**Comment by danchamp** [comment]
Closed by #63 and #64
