### ISSUE TITLE
Block

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_guides#8]
This module provides a block that then needs to be placed.

This means that the profile will need to place the blocks; and users installing separately will need an installation guide telling them to do the same manually.
Or 
If it works add output into the node preprocess and make them available to the templates, providing default templates.

See also similar issue for step-by-step localgovdrupal/localgov_step_by_step#1
And similar where the values go into the template localgovdrupal/localgov_services#43

**Comment by stephen-cox** [comment]
We're already placing blocks for service page stuff in the right-hand sidebar. It makes sense to me to keep this and place it during install for the localgov_theme. Placing blocks provides some flexibility particularly as these are required for navigation.

**Comment by ekes** [comment]
So localgovdrupal/localgov_step_by_step#1 at the moment has the blocks in optional configuration with 'bartik' an the 'readme' has instructions to change the theme so it gets imported to the correct theme.

I'm thinking there's got to be a nicer way of defaulting them on in the cases that it's installed outside the profile. I assuming the profile settings will be outside of this module - or maybe also dependent an in this module?

**Comment by ekes** [comment]
See also note about prev/next template links and contents in block comment on the PR https://github.com/localgovdrupal/localgov/pull/76#issuecomment-644828711

**Comment by stephen-cox** [comment]
What did we end up agreeing to on this?

My initial thought was to just define a block plugin that adds the prev and next links and have that placed at the bottom of the page. But we also discussed adding pseudo fields that can be placed through the node display. Step by step includes content blocks for this.

It's already going to be necessary to place the guide page navigation block so doing the same for the prev and next navigation links makes sense to me.

**Comment by ekes** [comment]
We didn't decide anything really. I'm a bit lost on all the differences of implementation on guides and step-by-step at this point. Finn suggested a call to go through them.

I think everything is now blocks in services. There's nothing that needs special template variables? So for consistency this as well.

Making stuff available as extra fields (pseudo fields) would have the bonus of not having to do stuff with the blocks when installed outside the profile.

**Comment by stephen-cox** [comment]
Any objection to making these all block plugins and adding some optional config to install these if the localgov_theme exists? 

This makes sense to me as they're navigational elements that might want to be put in different places on different sites. I can add some install documentation on adding the blocks if not using the localgov theme.

**Comment by ekes** [comment]
Go for it.

We can sort another issue to maybe make it smoother for people installing outside of the profile; but it seems a nice to have at this point.
